INSERT INTO articles (article, name, brand, price, stock, shop_url) VALUES
-- Тормозная система
('BP-2134', 'Тормозные колодки передние', 'Brembo', 3200, 8, 'https://www.autodoc.ru/search/by-text/?search=Brembo+BP-2134'),
('BD-5521', 'Тормозные диски передние', 'Brembo', 5800, 4, 'https://www.autodoc.ru/search/by-text/?search=Brembo+тормозные+диски'),
('BR-1190', 'Тормозные колодки задние', 'TRW', 2100, 12, 'https://www.autodoc.ru/search/by-text/?search=TRW+тормозные+колодки+задние'),
('BF-3310', 'Тормозная жидкость DOT-4 1L', 'Castrol', 680, 30, 'https://www.autodoc.ru/search/by-text/?search=Castrol+DOT4'),
('BH-7721', 'Шланг тормозной передний', 'Bosch', 950, 6, 'https://www.autodoc.ru/search/by-text/?search=Bosch+шланг+тормозной'),
('BC-4450', 'Тормозной суппорт передний', 'TRW', 7200, 2, 'https://www.autodoc.ru/search/by-text/?search=TRW+суппорт+тормозной'),
('BM-9920', 'Тормозной барабан задний', 'ATE', 3400, 5, 'https://www.autodoc.ru/search/by-text/?search=ATE+тормозной+барабан'),
-- Масла и жидкости
('OE-5W30', 'Масло моторное 5W-30 4L', 'Castrol', 2800, 20, 'https://www.autodoc.ru/search/by-text/?search=Castrol+5W-30'),
('OE-5W40', 'Масло моторное 5W-40 4L', 'Mobil1', 3200, 18, 'https://www.autodoc.ru/search/by-text/?search=Mobil1+5W-40'),
('OT-ATF', 'Масло трансмиссионное ATF 1L', 'ZF', 1200, 10, 'https://www.autodoc.ru/search/by-text/?search=ZF+ATF+масло'),
('OG-75W90', 'Масло редуктора 75W-90 1L', 'Castrol', 950, 8, 'https://www.autodoc.ru/search/by-text/?search=Castrol+75W-90'),
('OC-G12', 'Антифриз G12 красный 5L', 'FELIX', 890, 25, 'https://www.autodoc.ru/search/by-text/?search=FELIX+антифриз+G12'),
('OP-WF', 'Жидкость омывателя летняя 5L', 'Turtle Wax', 380, 40, 'https://www.autodoc.ru/search/by-text/?search=омывающая+жидкость+летняя'),
-- Фильтры
('FF-5521', 'Масляный фильтр', 'Mann', 450, 24, 'https://www.autodoc.ru/search/by-text/?search=Mann+масляный+фильтр'),
('FA-2210', 'Воздушный фильтр', 'Mann', 680, 15, 'https://www.autodoc.ru/search/by-text/?search=Mann+воздушный+фильтр'),
('FC-3300', 'Фильтр салона (угольный)', 'Mann', 890, 18, 'https://www.autodoc.ru/search/by-text/?search=Mann+фильтр+салона'),
('FT-6600', 'Топливный фильтр', 'Bosch', 1200, 10, 'https://www.autodoc.ru/search/by-text/?search=Bosch+топливный+фильтр'),
-- Подвеска
('TR-3300', 'Амортизатор передний', 'KYB', 5600, 2, 'https://www.autodoc.ru/search/by-text/?search=KYB+амортизатор+передний'),
('TR-3301', 'Амортизатор задний', 'KYB', 4800, 3, 'https://www.autodoc.ru/search/by-text/?search=KYB+амортизатор+задний'),
('SB-1100', 'Стойка стабилизатора передняя', 'Lemforder', 980, 8, 'https://www.autodoc.ru/search/by-text/?search=Lemforder+стойка+стабилизатора'),
('SB-1101', 'Стойка стабилизатора задняя', 'Lemforder', 920, 6, 'https://www.autodoc.ru/search/by-text/?search=Lemforder+стойка+стабилизатора+задняя'),
('SA-2200', 'Сайлентблок переднего рычага', 'Febi', 650, 12, 'https://www.autodoc.ru/search/by-text/?search=Febi+сайлентблок+рычага'),
('SA-2201', 'Сайлентблок заднего рычага', 'Febi', 580, 10, 'https://www.autodoc.ru/search/by-text/?search=Febi+сайлентблок+задний'),
('BR-4400', 'Шаровая опора передняя', 'TRW', 1800, 7, 'https://www.autodoc.ru/search/by-text/?search=TRW+шаровая+опора'),
('WB-5500', 'Подшипник ступицы передний', 'SKF', 3200, 5, 'https://technobearing.ru/search/?q=SKF+ступичный+подшипник'),
('WB-5501', 'Подшипник ступицы задний', 'SKF', 2900, 4, 'https://technobearing.ru/search/?q=SKF+подшипник+задний'),
('SL-7700', 'Пружина передняя', 'Eibach', 4200, 3, 'https://stancebazztards.ru/index.php?route=product/search&search=Eibach+пружина'),
('SL-7701', 'Пружина задняя', 'Eibach', 3800, 4, 'https://stancebazztards.ru/index.php?route=product/search&search=Eibach+пружина+задняя'),
('RN-3310', 'Рычаг передний нижний', 'Lemforder', 6800, 2, 'https://www.autodoc.ru/search/by-text/?search=Lemforder+рычаг+передний'),
('TS-8800', 'Тяга рулевая', 'TRW', 2400, 5, 'https://www.autodoc.ru/search/by-text/?search=TRW+тяга+рулевая'),
('TE-9900', 'Наконечник рулевой тяги', 'Lemforder', 1100, 9, 'https://www.autodoc.ru/search/by-text/?search=Lemforder+наконечник+рулевой'),
-- ГРМ и двигатель
('BE-1190', 'Ремень ГРМ', 'Gates', 2100, 6, 'https://www.autodoc.ru/search/by-text/?search=Gates+ремень+ГРМ'),
('TK-2200', 'Комплект ГРМ с роликами', 'Gates', 4800, 4, 'https://www.autodoc.ru/search/by-text/?search=Gates+комплект+ГРМ'),
('VP-3310', 'Помпа охлаждения', 'Bosch', 3600, 3, 'https://www.autodoc.ru/search/by-text/?search=Bosch+помпа+охлаждения'),
('TT-4400', 'Ролик натяжной ремня ГРМ', 'INA', 1800, 6, 'https://www.autodoc.ru/search/by-text/?search=INA+ролик+натяжной'),
('TR-5500', 'Ролик обводной', 'INA', 1400, 5, 'https://www.autodoc.ru/search/by-text/?search=INA+ролик+обводной'),
('GS-6600', 'Прокладка ГБЦ', 'Elring', 3200, 3, 'https://www.autodoc.ru/search/by-text/?search=Elring+прокладка+ГБЦ'),
('TS-7700', 'Термостат', 'Wahler', 1600, 7, 'https://www.autodoc.ru/search/by-text/?search=Wahler+термостат'),
('SS-8800', 'Сальник коленвала передний', 'Elring', 480, 10, 'https://www.autodoc.ru/search/by-text/?search=Elring+сальник+коленвала'),
('SS-8801', 'Сальник коленвала задний', 'Elring', 520, 8, 'https://www.autodoc.ru/search/by-text/?search=Elring+сальник+коленвала+задний'),
-- Свечи и система зажигания
('SP-7892', 'Свечи зажигания (к-т 4 шт)', 'NGK', 1800, 0, 'https://www.autodoc.ru/search/by-text/?search=NGK+свечи+зажигания'),
('SC-1100', 'Свечи зажигания иридиевые (к-т)', 'NGK', 3600, 5, 'https://www.autodoc.ru/search/by-text/?search=NGK+иридиевые+свечи'),
('IC-2200', 'Катушка зажигания', 'Bosch', 4200, 4, 'https://www.autodoc.ru/search/by-text/?search=Bosch+катушка+зажигания'),
('HC-3300', 'Высоковольтные провода', 'NGK', 2400, 6, 'https://www.autodoc.ru/search/by-text/?search=NGK+высоковольтные+провода'),
-- Трансмиссия и сцепление
('CK-1100', 'Комплект сцепления', 'LuK', 9800, 2, 'https://www.autodoc.ru/search/by-text/?search=LuK+комплект+сцепления'),
('CB-2200', 'Выжимной подшипник', 'LuK', 1800, 5, 'https://technobearing.ru/search/?q=LuK+выжимной+подшипник'),
('CD-3300', 'Диск сцепления', 'LuK', 4200, 3, 'https://www.autodoc.ru/search/by-text/?search=LuK+диск+сцепления'),
('CV-4400', 'ШРУС наружный комплект', 'GKN', 5800, 3, 'https://www.autodoc.ru/search/by-text/?search=GKN+ШРУС+наружный'),
('CV-4401', 'ШРУС внутренний комплект', 'GKN', 4600, 2, 'https://www.autodoc.ru/search/by-text/?search=GKN+ШРУС+внутренний'),
('PW-5500', 'Пыльник ШРУСа внешний', 'SKF', 680, 8, 'https://technobearing.ru/search/?q=SKF+пыльник+ШРУСа'),
-- Выхлопная система
('EK-1100', 'Катализатор', 'Bosal', 18500, 1, 'https://www.autodoc.ru/search/by-text/?search=Bosal+катализатор'),
('EM-2200', 'Глушитель основной', 'Bosal', 8900, 2, 'https://www.autodoc.ru/search/by-text/?search=Bosal+глушитель'),
('EG-3300', 'Прокладка выпускного коллектора', 'Elring', 890, 6, 'https://www.autodoc.ru/search/by-text/?search=Elring+прокладка+выпускного'),
('EF-4400', 'Гофра выхлопной трубы', 'Bosal', 1200, 5, 'https://www.autodoc.ru/search/by-text/?search=Bosal+гофра+выхлоп'),
-- Электрика
('AL-1100', 'Аккумулятор 60Ah', 'Bosch', 6800, 4, 'https://www.autodoc.ru/search/by-text/?search=Bosch+аккумулятор+60'),
('AL-1101', 'Аккумулятор 74Ah', 'Varta', 8200, 3, 'https://www.autodoc.ru/search/by-text/?search=Varta+аккумулятор+74'),
('GN-2200', 'Генератор', 'Bosch', 12500, 1, 'https://www.autodoc.ru/search/by-text/?search=Bosch+генератор'),
('ST-3300', 'Стартер', 'Bosch', 9800, 2, 'https://www.autodoc.ru/search/by-text/?search=Bosch+стартер'),
('LH-4400', 'Фара передняя левая', 'Hella', 8900, 2, 'https://www.autodoc.ru/search/by-text/?search=Hella+фара+левая'),
('LH-4401', 'Фара передняя правая', 'Hella', 8900, 2, 'https://www.autodoc.ru/search/by-text/?search=Hella+фара+правая'),
('LT-5500', 'Лампа H4 (к-т 2 шт)', 'Osram', 980, 15, 'https://www.autodoc.ru/search/by-text/?search=Osram+H4'),
('LT-5501', 'Лампа H7 (к-т 2 шт)', 'Philips', 1200, 12, 'https://www.autodoc.ru/search/by-text/?search=Philips+H7'),
('LX-6600', 'Лампа ксенон D2S', 'Osram', 4800, 4, 'https://www.autodoc.ru/search/by-text/?search=Osram+D2S+ксенон'),
('SS-7700', 'Датчик ABS передний', 'Bosch', 2800, 3, 'https://www.autodoc.ru/search/by-text/?search=Bosch+датчик+ABS'),
('SO-8800', 'Датчик кислорода (лямбда)', 'Bosch', 3400, 3, 'https://www.autodoc.ru/search/by-text/?search=Bosch+датчик+кислорода'),
('SC-9900', 'Датчик коленвала', 'Bosch', 2200, 4, 'https://www.autodoc.ru/search/by-text/?search=Bosch+датчик+коленвала'),
-- Система охлаждения
('RD-1100', 'Радиатор охлаждения', 'Nissens', 9800, 2, 'https://www.autodoc.ru/search/by-text/?search=Nissens+радиатор'),
('RD-1101', 'Радиатор кондиционера', 'Nissens', 7200, 2, 'https://www.autodoc.ru/search/by-text/?search=Nissens+радиатор+кондиционера'),
('EF-2200', 'Вентилятор радиатора', 'Nissens', 4800, 2, 'https://www.autodoc.ru/search/by-text/?search=Nissens+вентилятор'),
('HO-3300', 'Шланг радиатора верхний', 'Gates', 980, 6, 'https://www.autodoc.ru/search/by-text/?search=Gates+шланг+радиатора'),
('HO-3301', 'Шланг радиатора нижний', 'Gates', 920, 5, 'https://www.autodoc.ru/search/by-text/?search=Gates+шланг+нижний'),
-- Рулевое управление
('PS-1100', 'Рейка рулевая', 'TRW', 24500, 1, 'https://www.autodoc.ru/search/by-text/?search=TRW+рейка+рулевая'),
('PK-2200', 'Насос ГУР', 'TRW', 12800, 1, 'https://www.autodoc.ru/search/by-text/?search=TRW+насос+ГУР'),
('PF-3300', 'Жидкость ГУР 1L', 'Febi', 680, 12, 'https://www.autodoc.ru/search/by-text/?search=Febi+жидкость+ГУР'),
-- Кузов и резиновые изделия
('WI-1100', 'Щётки стеклоочистителя (пара)', 'Bosch', 1200, 14, 'https://www.autodoc.ru/search/by-text/?search=Bosch+щётки+стеклоочистителя'),
('WP-2200', 'Насос омывателя', 'Bosch', 1800, 5, 'https://www.autodoc.ru/search/by-text/?search=Bosch+насос+омывателя'),
('DL-3300', 'Замок двери передней левой', 'Hella', 3200, 2, 'https://www.autodoc.ru/search/by-text/?search=Hella+замок+двери'),
('MR-4400', 'Зеркало боковое левое', 'Hella', 5400, 2, 'https://www.autodoc.ru/search/by-text/?search=Hella+зеркало+левое'),
('BM-5500', 'Бампер передний', 'Original', 15800, 1, 'https://www.autodoc.ru/search/by-text/?search=бампер+передний'),
-- Подшипники (Technobearing)
('BRG-6205', 'Подшипник 6205 (25x52x15)', 'SKF', 380, 20, 'https://technobearing.ru/search/?q=6205'),
('BRG-6305', 'Подшипник 6305 (25x62x17)', 'FAG', 520, 15, 'https://technobearing.ru/search/?q=6305'),
('BRG-6206', 'Подшипник 6206 (30x62x16)', 'SKF', 420, 18, 'https://technobearing.ru/search/?q=6206'),
('BRG-6306', 'Подшипник 6306 (30x72x19)', 'FAG', 580, 12, 'https://technobearing.ru/search/?q=6306'),
('BRG-NJ205', 'Роликоподшипник NJ205', 'SKF', 980, 8, 'https://technobearing.ru/search/?q=NJ205'),
-- Ремни приводные (Technobearing)
('BLT-AVX13', 'Ремень клиновой AVX13x1000', 'Gates', 480, 10, 'https://technobearing.ru/search/?q=AVX13+ремень'),
('BLT-6PK', 'Ремень поликлиновой 6PK1750', 'Gates', 1200, 8, 'https://technobearing.ru/search/?q=6PK1750'),
('BLT-5PK', 'Ремень поликлиновой 5PK1545', 'Continental', 980, 6, 'https://technobearing.ru/search/?q=5PK1545'),
-- Расходники тюнинг (Stancebazztards)
('SPR-EIB-F', 'Пружины спортивные перед. Eibach Pro-Kit', 'Eibach', 18900, 2, 'https://stancebazztards.ru/index.php?route=product/search&search=Eibach+Pro-Kit'),
('SPR-EIB-R', 'Пружины спортивные зад. Eibach Pro-Kit', 'Eibach', 16800, 2, 'https://stancebazztards.ru/index.php?route=product/search&search=Eibach+задние'),
('COI-BC', 'Койловеры BC Racing BR-серия', 'BC Racing', 68000, 1, 'https://stancebazztards.ru/index.php?route=product/search&search=BC+Racing'),
('PAD-AP', 'Тормозные колодки спортивные AP Racing', 'AP Racing', 12400, 3, 'https://stancebazztards.ru/index.php?route=product/search&search=AP+Racing+колодки'),
('DISC-AP', 'Тормозные диски перфорированные AP Racing', 'AP Racing', 22000, 2, 'https://stancebazztards.ru/index.php?route=product/search&search=AP+Racing+диски'),
('FLUID-MT', 'Масло трансмиссионное Motul GEAR 300 75W90', 'Motul', 2400, 6, 'https://stancebazztards.ru/index.php?route=product/search&search=Motul+GEAR+300'),
-- Прочее
('GS-1100', 'Набор прокладок двигателя', 'Elring', 4800, 3, 'https://www.autodoc.ru/search/by-text/?search=Elring+набор+прокладок'),
('ST-2200', 'Стойка стекла задней левой', 'Stabilus', 2200, 4, 'https://www.autodoc.ru/search/by-text/?search=Stabilus+стойка+стекла'),
('EX-3300', 'Хомут глушителя 50мм', 'Bosal', 280, 25, 'https://www.autodoc.ru/search/by-text/?search=Bosal+хомут+глушителя')
